#
# Copyright: Copyright (c) 2026 Veevx Inc. All rights reserved.
# Author: Vijayvithal <jvs@veevx.com>
# Created on: 2026-02-04
# Description: A brief description of the file's purpose.
#
#
i2c:
	peakrdl regblock --cpuif apb4-flat --default-reset arst_n i2c.rdl -o ../verilog
