// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module I2C_Reg (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [5:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input I2C_Reg_pkg::I2C_Reg__in_t hwif_in,
        output I2C_Reg_pkg::I2C_Reg__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[5:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic Commands;
        logic Status;
        logic Cfg;
        logic Wdata;
        logic Rdata;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.Commands = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.Status = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.Cfg = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.Wdata = cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.Rdata = cpuif_req_masked & (cpuif_addr == 6'h20);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } start;
            struct {
                logic next;
                logic load_next;
            } read;
            struct {
                logic next;
                logic load_next;
            } write;
            struct {
                logic next;
                logic load_next;
            } write_multiple;
            struct {
                logic next;
                logic load_next;
            } stop;
            struct {
                logic [6:0] next;
                logic load_next;
            } addr;
        } Commands;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } prescale;
            struct {
                logic next;
                logic load_next;
            } stop_on_idle;
        } Cfg;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } wdata;
            struct {
                logic next;
                logic load_next;
            } wlast;
        } Wdata;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } rdata;
            struct {
                logic next;
                logic load_next;
            } rlast;
        } Rdata;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } start;
            struct {
                logic value;
            } read;
            struct {
                logic value;
            } write;
            struct {
                logic value;
            } write_multiple;
            struct {
                logic value;
            } stop;
            struct {
                logic [6:0] value;
            } addr;
        } Commands;
        struct {
            struct {
                logic [15:0] value;
            } prescale;
            struct {
                logic value;
            } stop_on_idle;
        } Cfg;
        struct {
            struct {
                logic [7:0] value;
            } wdata;
            struct {
                logic value;
            } wlast;
        } Wdata;
        struct {
            struct {
                logic [7:0] value;
            } rdata;
            struct {
                logic value;
            } rlast;
        } Rdata;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: I2C_Reg.Commands.start
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.start.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.start.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.Commands.start.next = next_c;
        field_combo.Commands.start.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.start.value <= 1'h0;
        end else begin
            if(field_combo.Commands.start.load_next) begin
                field_storage.Commands.start.value <= field_combo.Commands.start.next;
            end
        end
    end
    assign hwif_out.Commands.start.value = field_storage.Commands.start.value;
    // Field: I2C_Reg.Commands.read
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.read.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.read.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.Commands.read.next = next_c;
        field_combo.Commands.read.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.read.value <= 1'h0;
        end else begin
            if(field_combo.Commands.read.load_next) begin
                field_storage.Commands.read.value <= field_combo.Commands.read.next;
            end
        end
    end
    assign hwif_out.Commands.read.value = field_storage.Commands.read.value;
    // Field: I2C_Reg.Commands.write
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.write.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.write.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.Commands.write.next = next_c;
        field_combo.Commands.write.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.write.value <= 1'h0;
        end else begin
            if(field_combo.Commands.write.load_next) begin
                field_storage.Commands.write.value <= field_combo.Commands.write.next;
            end
        end
    end
    assign hwif_out.Commands.write.value = field_storage.Commands.write.value;
    // Field: I2C_Reg.Commands.write_multiple
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.write_multiple.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.write_multiple.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.Commands.write_multiple.next = next_c;
        field_combo.Commands.write_multiple.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.write_multiple.value <= 1'h0;
        end else begin
            if(field_combo.Commands.write_multiple.load_next) begin
                field_storage.Commands.write_multiple.value <= field_combo.Commands.write_multiple.next;
            end
        end
    end
    assign hwif_out.Commands.write_multiple.value = field_storage.Commands.write_multiple.value;
    // Field: I2C_Reg.Commands.stop
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.stop.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.stop.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.Commands.stop.next = next_c;
        field_combo.Commands.stop.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.stop.value <= 1'h0;
        end else begin
            if(field_combo.Commands.stop.load_next) begin
                field_storage.Commands.stop.value <= field_combo.Commands.stop.next;
            end
        end
    end
    assign hwif_out.Commands.stop.value = field_storage.Commands.stop.value;
    // Field: I2C_Reg.Commands.addr
    always_comb begin
        automatic logic [6:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Commands.addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.Commands && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Commands.addr.value & ~decoded_wr_biten[14:8]) | (decoded_wr_data[14:8] & decoded_wr_biten[14:8]);
            load_next_c = '1;
        end
        field_combo.Commands.addr.next = next_c;
        field_combo.Commands.addr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Commands.addr.value <= 7'h0;
        end else begin
            if(field_combo.Commands.addr.load_next) begin
                field_storage.Commands.addr.value <= field_combo.Commands.addr.next;
            end
        end
    end
    assign hwif_out.Commands.addr.value = field_storage.Commands.addr.value;
    // Field: I2C_Reg.Cfg.prescale
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Cfg.prescale.value;
        load_next_c = '0;
        if(decoded_reg_strb.Cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Cfg.prescale.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.Cfg.prescale.next = next_c;
        field_combo.Cfg.prescale.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Cfg.prescale.value <= 16'h0;
        end else begin
            if(field_combo.Cfg.prescale.load_next) begin
                field_storage.Cfg.prescale.value <= field_combo.Cfg.prescale.next;
            end
        end
    end
    assign hwif_out.Cfg.prescale.value = field_storage.Cfg.prescale.value;
    // Field: I2C_Reg.Cfg.stop_on_idle
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Cfg.stop_on_idle.value;
        load_next_c = '0;
        if(decoded_reg_strb.Cfg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Cfg.stop_on_idle.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end
        field_combo.Cfg.stop_on_idle.next = next_c;
        field_combo.Cfg.stop_on_idle.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Cfg.stop_on_idle.value <= 1'h0;
        end else begin
            if(field_combo.Cfg.stop_on_idle.load_next) begin
                field_storage.Cfg.stop_on_idle.value <= field_combo.Cfg.stop_on_idle.next;
            end
        end
    end
    assign hwif_out.Cfg.stop_on_idle.value = field_storage.Cfg.stop_on_idle.value;
    // Field: I2C_Reg.Wdata.wdata
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Wdata.wdata.value;
        load_next_c = '0;
        if(decoded_reg_strb.Wdata && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Wdata.wdata.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.Wdata.wdata.next = next_c;
        field_combo.Wdata.wdata.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Wdata.wdata.value <= 8'h0;
        end else begin
            if(field_combo.Wdata.wdata.load_next) begin
                field_storage.Wdata.wdata.value <= field_combo.Wdata.wdata.next;
            end
        end
    end
    assign hwif_out.Wdata.wdata.value = field_storage.Wdata.wdata.value;
    // Field: I2C_Reg.Wdata.wlast
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Wdata.wlast.value;
        load_next_c = '0;
        if(decoded_reg_strb.Wdata && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Wdata.wlast.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.Wdata.wlast.next;
            load_next_c = '1;
        end
        field_combo.Wdata.wlast.next = next_c;
        field_combo.Wdata.wlast.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Wdata.wlast.value <= 1'h0;
        end else begin
            if(field_combo.Wdata.wlast.load_next) begin
                field_storage.Wdata.wlast.value <= field_combo.Wdata.wlast.next;
            end
        end
    end
    assign hwif_out.Wdata.wlast.value = field_storage.Wdata.wlast.value;
    // Field: I2C_Reg.Rdata.rdata
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Rdata.rdata.value;
        load_next_c = '0;
        if(decoded_reg_strb.Rdata && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Rdata.rdata.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.Rdata.rdata.next;
            load_next_c = '1;
        end
        field_combo.Rdata.rdata.next = next_c;
        field_combo.Rdata.rdata.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Rdata.rdata.value <= 8'h0;
        end else begin
            if(field_combo.Rdata.rdata.load_next) begin
                field_storage.Rdata.rdata.value <= field_combo.Rdata.rdata.next;
            end
        end
    end
    // Field: I2C_Reg.Rdata.rlast
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.Rdata.rlast.value;
        load_next_c = '0;
        if(decoded_reg_strb.Rdata && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.Rdata.rlast.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.Rdata.rlast.next;
            load_next_c = '1;
        end
        field_combo.Rdata.rlast.next = next_c;
        field_combo.Rdata.rlast.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.Rdata.rlast.value <= 1'h0;
        end else begin
            if(field_combo.Rdata.rlast.load_next) begin
                field_storage.Rdata.rlast.value <= field_combo.Rdata.rlast.next;
            end
        end
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[5];
    assign readback_array[0][0:0] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.start.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.read.value : '0;
    assign readback_array[0][2:2] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.write.value : '0;
    assign readback_array[0][3:3] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.write_multiple.value : '0;
    assign readback_array[0][4:4] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.stop.value : '0;
    assign readback_array[0][7:5] = '0;
    assign readback_array[0][14:8] = (decoded_reg_strb.Commands && !decoded_req_is_wr) ? field_storage.Commands.addr.value : '0;
    assign readback_array[0][31:15] = '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.Status && !decoded_req_is_wr) ? hwif_in.Status.busy.next : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.Status && !decoded_req_is_wr) ? hwif_in.Status.bus_control.next : '0;
    assign readback_array[1][2:2] = (decoded_reg_strb.Status && !decoded_req_is_wr) ? hwif_in.Status.bus_active.next : '0;
    assign readback_array[1][3:3] = (decoded_reg_strb.Status && !decoded_req_is_wr) ? hwif_in.Status.missed_ack.next : '0;
    assign readback_array[1][31:4] = '0;
    assign readback_array[2][15:0] = (decoded_reg_strb.Cfg && !decoded_req_is_wr) ? field_storage.Cfg.prescale.value : '0;
    assign readback_array[2][16:16] = (decoded_reg_strb.Cfg && !decoded_req_is_wr) ? field_storage.Cfg.stop_on_idle.value : '0;
    assign readback_array[2][31:17] = '0;
    assign readback_array[3][7:0] = (decoded_reg_strb.Wdata && !decoded_req_is_wr) ? field_storage.Wdata.wdata.value : '0;
    assign readback_array[3][8:8] = (decoded_reg_strb.Wdata && !decoded_req_is_wr) ? field_storage.Wdata.wlast.value : '0;
    assign readback_array[3][31:9] = '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.Rdata && !decoded_req_is_wr) ? field_storage.Rdata.rdata.value : '0;
    assign readback_array[4][8:8] = (decoded_reg_strb.Rdata && !decoded_req_is_wr) ? field_storage.Rdata.rlast.value : '0;
    assign readback_array[4][31:9] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<5; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
